chestDetails = {
	{"Reward 66", "Destiny Islands", "Day1"},
	{"Reward 9E", "Chamber 6", "White Trinity"},
	{"Reward 3f", "1st District", "Blizzard Magic"},
	{"Postcard", "1st District"},
	{"Postcard", "2nd District"},
	{"Mythril Shard", "2nd District"},
	{"Mega-Potion", "2nd District"},
	{"Potion", "Alleyway"},
	{"Pretty Stone", "Alleyway"},
	{"Potion", "Alleyway"},
	{"Mythril", "Green Room"},
	{"Reward 40", "Green Room"},
	{"Pretty Stone", "Red Room"},
	{"Reward 41", "Mystical House", "Fire Magic", "High Jump OR Yellow Trinity"},
	{"Mythril Shard", "Accessory Shop"},
	{"Reward 42", "Secret Waterway", "White Trinity"},
	{"Reward 33", "Gepetto's House", "High Jump OR Glide"},
	{"Postcard", "1st District", "Blue Trinity OR Glide"},
	{"Dalmatians 23", "Moonlight Hill", "White Trinity"},
	{"Fira-G", "Bridge", "Jack-In-The-Box"},
	{"Jack-In-The-Box", "Boneyard"},
	{"Defense Up", "Bridge", "High Jump OR Glide", "Jack-In-The-Box"},
	{"Reward a0", "Cemetery", "Jack-In-The-Box"},
	{"Dalmatians 22", "Cemetery", "Jack-In-The-Box"},
	{"Gummi", "Cemetery", "Jack-In-The-Box"},
	{"Reward 9f", "Oogie Manor", "Jack-In-The-Box"},
	{"Mega-Ether", "Oogie Manor", "Jack-In-The-Box"},
	{"Dalmatians 14", "Oogie Manor", "Jack-In-The-Box"},
	{"Mythril Shard", "Oogie Manor", "Red Trinity", "Jack-In-The-Box"},
	{"Power Up", "Guillotine Square", "High Jump OR Glide"},
	{"Elixir", "Guillotine Square", "Glide"},
	{"Ether", "Oogie Manor", "Jack-In-The-Box"},
	{"Ether", "Oogie Manor", "Jack-In-The-Box"},
	{"Meteor-G", "Bridge", "Jack-In-The-Box"},
	{"Holy-G", "Cemetery", "Jack-In-The-Box"},
	{"Thundara-G", "Guillotine Square"},
	{"Dalmatians 24", "Guillotine Square", "Glide"},
	{"Mega-Potion", "Coliseum Gates"},
	{"Dalmatians 8", "Coliseum Gates", "Blue Trinity"},
	{"Reward 55", "Coliseum Gates", "Blue Trinity"},
	{"Reward 56", "Coliseum Gates", "White Trinity"},
	{"Gummi", "Coliseum Gates", "Blizzara Magic"},
	{"Reward 9a", "Coliseum Gates", "Blizzaga Magic"},
	{"Dalmatians 1", "Mystical House", "Glide", "Fire Magic"},
	{"Dalmatians 2", "Alleyway", "Red Trinity"},
	{"Dalmatians 3", "Item Workshop", "Green Trinity"},
	{"Dalmatians 4", "Secret Waterway"},
	{"Reward 74", "Rabbit hole", "Green Trinity"},
	{"Reward 43", "Rabbit hole"},
	{"Reward 44", "Rabbit hole"},
	{"Reward 45", "Rabbit hole"},
	{"Reward 46", "Bizarre Room", "Green Trinity"},
	{"Megalixir", "Final Rest", "HB1", "HB2", "EotW"},
	{"Reward 8e", "World Terminus", "HB1", "HB2", "EotW"},
	{"Thundara-G", "Queen's Castle"},
	{"Dalmatians 5", "Queen's Castle", "Evidence OR High Jump OR Glide"},
	{"Meteor-G", "Queen's Castle"},
	{"Thundara-G", "Lotus Forest", "Thunder Magic", "Evidence"},
	{"Dalmatians 20", "Lotus Forest", "Thunder Magic"},
	{"Reward 47", "Lotus Forest", "Glide OR High Jump"},
	{"Dalmatians 6", "Lotus Forest"},
	{"Scan-G", "Lotus Forest"},
	{"Defense Up", "Bizarre Room"},
	{"Dalmatians 19", "Chamber 3"},
	{"Flare-G", "Tea Party Garden", "Glide OR High Jump", "Evidence OR Glide"},
	{"Dalmatians 7", "Tea Party Garden", "Glide OR High Jump", "Evidence OR Glide"},
	{"Reward 99", "Tea Party Garden", "Evidence OR Glide"},
	{"Reward 32", "Tea Party Garden", "Glide OR High Jumpra", "Evidence OR Glide"},
	{"Reward 48", "Lotus Forest", "White Trinity"},
	{"Megalixir", "World Terminus", "EotW"},
	{"Reward 8d", "World Terminus", "EotW"},
	{"Reward 8c", "World Terminus", "EotW"},
	{"Reward 28", "Monstro: Mouth", "High Jump OR Glide"},
	{"Dalmatians 27", "Chamber 5"},
	{"Mega-Ether", "Chamber 5"},
	{"Thundaga-G", "Chamber 5"},
	{"Reward 49", "Tree House"},
	{"Reward 4a", "Tree House"},
	{"Dalmatians 9", "Hippos' Lagoon"},
	{"Mega-Potion", "Hippos' Lagoon"},
	{"Meteor-G", "Hippos' Lagoon"},
	{"Reward 78", "Ship: Cabin", "Green Trinity"},
	{"Mythril", "Jungle: Vines"},
	{"Dalmatians 10", "Jungle: Vines 2"},
	{"Thundara-G", "Climbing Trees", "Blue Trinity"},
	{"Reward 8b", "World Terminus", "EotW"},
	{"Mega-Ether", "Jungle: Tunnel"},
	{"Reward 4b", "Cavern of Hearts", "White Trinity", "Slides"},
	{"Dalmatians 12", "Camp", "Blue Trinity"},
	{"Mythril Shard", "Camp: Tent"},
	{"Mythril Shard", "Waterfall Cavern", "Slides"},
	{"Dalmatians 11", "Waterfall Cavern", "Slides"},
	{"Mythril", "Waterfall Cavern", "Slides"},
	{"Orichalcum", "Waterfall Cavern", "Slides"},
	{"Reward 72", "Jungle: Cliff"},
	{"Reward 73", "Jungle: Cliff"},
	{"Reward 75", "Tree House"},
	{"Reward 8a", "World Terminus", "EotW"},
	{"Reward 89", "World Terminus", "EotW"},
	{"Reward 88", "World Terminus", "EotW"},
	{"Reward 87", "World Terminus", "EotW"},
	{"Ultima-G", "Giant Crevasse", "EotW"},
	{"Flare-G", "Clock Tower", "Green Trinity"},
	{"Paper-G", "Ship: Hold", "Glide", "Green Trinity"},
	{"Dalmatians 29", "Ship: Hold", "Yellow Trinity"},
	{"Dalmatians 30", "Captain's Cabin", "Green Trinity"},
	{"Life-G", "Rising Falls"},
	{"Meteor-G", "Rising Falls"},
	{"Reward 58", "Rising Falls", "HB1", "HB2"},
	{"Dalmatians 31", "Rising Falls", "Blizzard Magic"},
	{"Reward 79", "Rising Falls", "Blizzard Magic"},
	{"Megalixir", "Rising Falls"},
	{"Dalmatians 32", "Castle Gates", "Dumbo OR HB1", "Gravity Magic"},
	{"Reward 59", "Castle Gates", "Dumbo OR HB1"},
	{"Haste2-G", "Castle Gates", "Dumbo OR HB1"},
	{"Orichalcum", "Great Crest", "HB1"},
	{"Thundaga-G", "Great Crest", "HB1"},
	{"Osmose-G", "High Tower", "HB1", "Gravity Magic"},
	{"Reward 5a", "High Tower", "HB1", "Gravity Magic"},
	{"Megalixir", "High Tower", "HB1"},
	{"Reward 5b", "Entrance Hall", "Dumbo"},
	{"Mythril Shard", "Hundred Acre Woods"},
	{"Reward 4c", "Hundred Acre Woods", "Page3"},
	{"Reward 9b", "Hundred Acre Woods", "Page3"},
	{"Reward 4d", "Hundred Acre Woods", "Page3"},
	{"Reward a7", "Giant Crevasse", "EotW", "Glide"},
	{"Reward a3", "Lift Stop", "HB1", "Khama", "Gravity Magic"},
	{"Osmose-G", "Lift Stop", "Dumbo OR HB1", "Khama", "Gravity Magic"},
	{"Reward a4", "Lift Stop", "HB1", "Khama", "Gravity Magic"},
	{"Dalmatians 33", "Lift Stop", "Dumbo OR HB1", "Khama", "Gravity Magic"},
	{"Orichalcum", "Lift Stop", "Dumbo OR HB1"},
	{"Mythril", "Base Level"},
	{"Paper-G", "Base Level"},
	{"Thundara-G", "Base Level"},
	{"Reward 7a", "Waterway"},
	{"Reward a5", "Waterway", "High Jump", "Blizzard Magic"},
	{"Thundaga-G", "Waterway"},
	{"Ultima-G", "Dungeon"},
	{"Thundaga-G", "Dungeon"},
	{"Drill-G", "Giant Crevasse", "EotW"},
	{"Reward a8", "Giant Crevasse", "EotW"},
	{"Full-Life-G", "Giant Crevasse", "EotW", "Glide"},
	{"Reward 82", "Final Dimension", "EotW"},
	{"Reward 80", "Final Dimension", "EotW"},
	{"Reward 7f", "Final Dimension", "EotW"},
	{"Reward 7b", "Final Dimension", "EotW"},
	{"Reward a6", "Grand Hall", "HB1", "HB2"},
	{"Reward 31", "Grand Hall", "HB1", "HB2"},
	{"Dalmatians 21", "Grand Hall", "HB1", "HB2"},
	{"Ultima-G", "Library", "Khama"},
	{"Thundaga-G", "Rising Falls", "White Trinity"},
	{"Mega-Potion", "Agrabah: Plaza"},
	{"Mega-Ether", "Agrabah: Plaza"},
	{"Reward 4e", "Agrabah: Plaza"},
	{"Mega-Potion", "Agrabah: Alley"},
	{"Thundara-G", "Agrabah: Bazaar"},
	{"Reward 4f", "Agrabah: Bazaar"},
	{"Mega-Ether", "Agrabah: Main Street"},
	{"Reward 9c", "Agrabah: Main Street"},
	{"Reward 50", "Agrabah: Main Street", "High Jump OR Glide"},
	{"Reward 76", "Palace Gates"},
	{"Dalmatians 18", "Palace Gates", "High Jump OR Glide"},
	{"Osmose-G", "Palace Gates", "Glide"},
	{"Reward 51", "Agrabah: Storage", "Green Trinity"},
	{"Mega-Potion", "Agrabah: Storage"},
	{"Mega-Ether", "Cave: Entrance"},
	{"Dalmatians 17", "Cave: Entrance", "High Jump OR Glide"},
	{"Elixir", "Cave: Hall"},
	{"Mythril Shard", "Cave: Hall"},
	{"Cottage", "Bottomless Hall"},
	{"Reward 52", "Bottomless Hall"},
	{"Reward 53", "Bottomless Hall"},
	{"Dalmatians 13", "Treasure Room"},
	{"Mythril Shard", "Treasure Room"},
	{"Thundara-G", "Treasure Room"},
	{"Defense Up", "Treasure Room"},
	{"Mythril", "Relic Chamber"},
	{"Reward 77", "Relic Chamber"},
	{"Reward 54", "Dark Chamber"},
	{"Meteor-G", "Dark Chamber"},
	{"Torn Page 3", "Dark Chamber"},
	{"Cottage", "Dark Chamber"},
	{"Thundara-G", "Silent Chamber", "Blue Trinity"},
	{"Haste2-G", "Hidden Room", "Yellow Trinity OR High Jump"},
	{"Dalmatians 16", "Hidden Room", "Yellow Trinity OR High Jump"},
	{"Scissors-G", "Aladdin's House"},
	{"Megalixir", "Aladdin's House"},
	{"Reward 9d", "Cave: Entrance", "White Trinity"},
	{"Dalmatians 28", "Ship: Hold", "Glide", "Green Trinity"},
	{"Meteor-G", "Ship: Galley"},
	{"Reward a1", "Ship: Hold", "Yellow Trinity"},
	{"Orichalcum", "Ship: Hold", "Yellow Trinity"},
	{"Reward a2", "Pirate Ship", "Green Trinity", "Glide"},
	{"Dalmatians 15", "Pirate Ship", "White Trinity", "Green Trinity", "Glide"},
	{"Flare-G", "Chamber 3"},
	{"Osmose-G", "Chamber 3"},
	{"Megalixir", "Chamber 6", "High Jump OR Glide"},
	{"Torn Page 2", "Chamber 6"},
	{"Reward 29", "Chamber 6", "High Jump OR Glide"},
	{"Dalmatians 26", "Chamber 6"},
	{"Mega-Ether", "Chamber 3"},
	{"Mythril", "Chamber 5"},
	{"Megalixir", "Chamber 2"},
	{"Cottage", "Chamber 2"},
	{"Reward 57", "Monstro: Mouth", "High Jump OR Glide", "Green Trinity"},
	{"Scan-G", "Monstro: Mouth"},
	{"Dalmatians 25", "Monstro: Mouth", "High Jump OR Glide"},
	{"Cottage", "Monstro: Mouth", "High Jump OR Glide"},
	{"Reward 27", "Monstro: Mouth"},
}