rewardDetails = {
	{"Elixir", "Defeat Leon", "Missable"},
	{"Dodge Roll", "End of TT"},
	{"Mega-Potion", "Aerith TT", "Missable"},
	{"Mermaid Kick", "Ursula 1"},
	{"Glide", "Neverland", "Green Trinity"},
	{"Superglide", "Chernabog", "EotW", "HB1", "HB2"},
	{"Fireglow", "Dragon Maleficent", "HB1"},
	{"Earthshine", "Secret Waterway"},
	{"Jungle King", "Deep Jungle", "Slides"},
	{"Three Wishes", "Agrabah"},
	{"Fairy Harp", "Neverland", "Green Trinity"},
	{"Pumpkinhead", "Halloween Town", "Jack-In-The-Box"},
	{"Crabclaw", "Atlantica", "Mermaid Kick"},
	{"Divine Rose", "Belle in HB2", "HB1", "HB2"},
	{"Lionheart", "Leon & Cloud Hades Cup", "HB1", "Entry Pass"},
	{"Metal Chocobo", "Cloud Hercules Cup", "Entry Pass"},
	{"Oathkeeper", "Kairi TT4", "HB1"},
	{"Genji Shield", "Yuffie Hades Cup", "Entry Pass"},
	{"Herc's Shield", "Hercules Cup", "Entry Pass"},
	{"Sonic Blade", "Olympus Coliseum", "Entry Pass"},
	{"Raven's Claw", "Anti-Sora", "Green Trinity"},
	{"Strike Raid", "Pegasus Cup", "Entry Pass"},
	{"Ragnarok", "Riku 2", "HB1"},
	{"Trinity Limit", "Hades Cup", "HB1", "Entry Pass"},
	{"Ars Arcanum", "Capt. Hook", "Green Trinity"},
	{"Cheer (Donald)", "Maleficent", "HB1"},
	{"Cheer (Goofy)", "Parasite Cage", "High Jump OR Glide"},
	{"Lord Fortune", "Fairy Godmother", "All Summons", "Fire Magic"},
	{"High Jump", "Chest", "-"},
	{"Watergleam", "Chest", "-"},
	{"Mythril", "Chest", "-"},
	{"Naturespark", "Hundred Acre Wood", "Page1"},
	{"Mythril Shard", "Hundred Acre Wood", "Page2"},
	{"Mythril", "Hundred Acre Wood", "Page4"},
	{"EXP Ring", "Hundred Acre Wood", "Page5"},
	{"Cheer (Sora)", "From Owl", "Page5"},
	{"Dream Shield", "Merlin", "Arts", "All Spells"},
	{"Olympia", "Olympus Coliseum", "Entry Pass"},
	{"Oblivion", "Chest", "-"},
	{"Mythril", "Chest", "-"},
	{"Wishing Star", "Chest", "-"},
	{"Mythril Shard", "Dalmatians' House", "42 Puppies"},
	{"Megalixir", "Dalmatians' House", "60 Puppies"},
	{"Orichalcum", "Dalmatians' House", "72 Puppies"},
	{"Tech Boost", "Dalmatians' House", "90 Puppies"},
	{"Brave Warrior", "Guard Armor"},
	{"Ifrit's Horn", "Trickmaster", "Evidence"},
	{"Inferno Band", "Cerberus", "Entry Pass"},
	{"White Fang", "Sabor 2", "Slides"},
	{"Ray of Light", "Pot Centipede"},
	{"Holy Circlet", "Oogie Boogie", "Jack-In-The-Box"},
	{"Omega Arts", "Behemoth", "HB1", "HB2"},
	{"Defense Up", "Chest", "-"},
	{"Elixir", "Chest", "-"},
	{"AP Up", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Camping Set", "Chest", "-"},
	{"Mega-Potion", "Chest", "-"},
	{"Megalixir", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Lady Luck", "Chest", "-"},
	{"Mega-Potion", "Chest", "-"},
	{"Protect Chain", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"AP Up", "Chest", "-"},
	{"Cottage", "Chest", "-"},
	{"Fire Ring", "Chest", "-"},
	{"Mythril", "Chest", "-"},
	{"Cottage", "Chest", "-"},
	{"Elixir", "Chest", "-"},
	{"Mega-Potion", "Chest", "-"},
	{"Protera Chain", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Violetta", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Defense Up", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Thundara Ring", "Chest", "-"},
	{"AP Up", "Chest", "-"},
	{"Spellbinder", "Merlin", "All Spells"},
	{"Dream Rod", "Merlin", "Max Spells"},
	{"Combo Plus", "Phil Cup Solo", "Entry Pass"},
	{"Orichalcum", "Pegasus Cup Solo", "Entry Pass"},
	{"Critical Plus", "Hercules Cup Solo", "Entry Pass"},
	{"Save the Queen", "Hades Cup Solo", "HB1", "Entry Pass"},
	{"Tech Boost", "Phil Cup Time Trial", "Entry Pass"},
	{"Dark Matter", "Pegasus Cup Time Trial", "Entry Pass"},
	{"Gravity Break", "Hercules Cup Time Trial", "Entry Pass"},
	{"Save the King", "Hades Cup Time Trial", "HB1", "Entry Pass"},
	{"Protect Chain", "Chest", "-"},
	{"Cottage", "Postcard 1", "Postcard 1"},
	{"Mythril Shard", "Postcard 2", "Postcard 2"},
	{"Mega-Potion", "Postcard 3", "Postcard 3"},
	{"Mega-Ether", "Postcard 4", "Postcard 4"},
	{"Mythril", "Postcard 5", "Postcard 5"},
	{"Elixir", "Postcard 6", "Postcard 6"},
	{"Megalixir", "Postcard 7", "Postcard 7"},
	{"Orichalcum", "Postcard 8", "Postcard 8"},
	{"AP Up", "Postcard 9", "Postcard 9"},
	{"Defense Up", "Postcard 10", "Postcard 10"},
	{"Mythril", "Dalmatians' House", "51 Puppies"},
	{"Mega-Potion", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Elixir", "Chest", "-"},
	{"Mythril", "Chest", "-"},
	{"Protera Chain", "Chest", "-"},
	{"Thunder Ring", "Chest", "-"},
	{"Protera Chain", "Chest", "-"},
	{"Blizzara Ring", "Chest", "-"},
	{"Fira Ring", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Pretty Stone", "Final Dimension", "EotW"},
	{"Mega-Potion", "Final Dimension", "EotW"},
	{"Mythril", "Final Dimension", "EotW"},
	{"Elixir", "Chest", "-"},
	{"Mythril Shard", "Chest", "-"},
	{"Pretty Stone", "Final Dimension", "EotW"},
	{"Cottage", "Chest", "-"},
	{"Gale", "Final Dimension", "EotW"},
	{"AP Up", "Final Dimension", "EotW"},
	{"Spirit Gem", "Chest", "-"},
	{"Thunder Gem", "Chest", "-"},
	{"Frost Gem", "Chest", "-"},
	{"Bright Gem", "Chest", "-"},
	{"Blaze Gem", "Chest", "-"},
	{"Lucid Gem", "Chest", "-"},
	{"Mighty Shield", "Chest", "-"},
	{"Elixir", "Chest", "-"},
	{"Elixir", "Jungle Slider", "Slides"},
	{"AP Up", "Jungle Slider", "Slides"},
	{"Dark Matter", "Jungle Slider", "Slides"},
	{"Defense Up", "Jungle Slider", "Slides"},
	{"Power Up", "Jungle Slider", "Slides"},
	{"Diamond Dust", "Ice Titan", "Entry Pass"},
	{"One-Winged Angel", "Sephiroth", "HB1", "HB2", "EotW", "Entry Pass"},
	{"Zantetsuken", "Kurt Zisa", "HB1", "HB2", "EotW"},
	{"EXP Necklace", "Unknown", "HB1", "HB2", "EotW"},
	{"Dark Matter", "Chest", "-"},
	{"Shiva Belt", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Ifrit Belt", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Orichalcum", "Chest", "-"},
	{"Ramuh Belt", "Chest", "-"},
	{"Royal Crown", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Dark Matter", "Chest", "-"},
	{"Meteor Strike", "Chest", "-"}
}
